GET http://localhost:3000/api/gameState/

###

GET http://localhost:3000/api/gameState/xf5bHSy7

###

PATCH http://localhost:3000/api/gameState/xf5bHSy7
Content-Type: application/json

{
    "countdownValue": 3
}

###

DELETE http://localhost:3000/api/gameState/