GET http://localhost:3000/api/gameStates/

###

GET http://localhost:3000/api/gameStates/9ahPNVRE

###

PATCH http://localhost:3000/api/gameStates/xf5bHSy7
Content-Type: application/json

{
    "countdownValue": 3
}

###

DELETE http://localhost:3000/api/gameStates/