GET http://localhost:3000/api/nodeRelations

###

GET http://localhost:3000/api/nodeRelations/51?stateId=190

###

POST http://localhost:3000/api/nodeRelations/14
Content-Type: application/json

{
    "point": 0,
    "creator": 2
}

###

DELETE http://localhost:3000/api/nodeRelations/14?point=0