GET http://localhost:3000/api/rooms

###

GET http://localhost:3000/api/rooms/xf5bHSy7

###

POST http://localhost:3000/api/rooms/
Content-Type: application/json

{
    "gameMode": "CLASSIC"
}

###

PATCH  http://localhost:3000/api/rooms/bPeQDJ75
Content-Type: application/json

{
    "inviteCode": "bPeQDJ12"
}

###

DELETE http://localhost:3000/api/rooms/vi82L2ZX