export const GAME_STATUS = {
    WAITING: "WAITING", 
    STARTING: "STARTING", 
    ONGOING: "ONGOING", 
    FINISHED: "FINISHED", 
    SUSPENDED: "SUSPENDED", 
    REDUNDANT: "REDUNDANT"
}

export const GAME_MODE = {
    CLASSIC: "CLASSIC",
    BESTOF3: "BESTOF3"
}

Object.freeze(GAME_STATUS)
Object.freeze(GAME_MODE)