name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: paper-soccer

      - name: Build project
        working-directory: ./paper-soccer
        run: npm run build
        env:
          VITE_SERVER_ADDRESS: ${{ secrets.VITE_SERVER_ADDRESS }}
          VITE_SERVER_PORT: ${{ secrets.VITE_SERVER_PORT }}
          VITE_ROOT_ROUTE: ${{ secrets.VITE_ROOT_ROUTE }}
          VITE_GITHUB_PAGES: ${{ secrets.VITE_GITHUB_PAGES }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./paper-soccer/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./paper-soccer/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./paper-soccer/dist